# Generated by Django 5.2.5 on 2025-09-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBS', '0002_project_delete_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
